boiforte/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('dashboards/', include('dashboards.urls')),
    path('register/', include('register.urls')),
    path('sales/', include('sales.urls')),
    path('users/', include('users.urls')),
    path('finances/', include('finances.urls')),
    path('siagri/', include('siagri.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'boiforte.views.handler404'
handler403 = 'boiforte.views.handler403'
handler500 = 'boiforte.views.handler500'

sales/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index_vendas, name='vendas.index'),
    path('new', views.vendas_new, name='vendas.new'),
    path('edit/<uuid:uuid>', views.vendas_edit, name='vendas.edit'),
    path('delete/<int:id>', views.vendas_delete, name='vendas.delete')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.users_index, name='users.index'),
    path('view/<int:id>', views.user_view, name='user.view'),
    path('edit/<int:id>', views.user_edit, name='user.edit'),
    path('new', views.user_new, name='user.new'),
    path('emails', views.users_emails, name='users.emails'),
]

register/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField
import uuid
# Create your models here.
class Cadastro_Municipios(models.Model):
    id = models.BigIntegerField(primary_key=True, verbose_name='Código Município')
    cod_uf = models.IntegerField(verbose_name='Código UF')
    sigla_uf = models.CharField(max_length=2, null=True, verbose_name='Sigla UF')
    nome_uf = models.CharField(max_length=255, null=True, verbose_name='Nome UF')
    nome_municipio = models.CharField(max_length=255, null=True, verbose_name='Nome Município')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = 'Cadastro Municípios'
    def __str__(self):
        return f"{self.nome_municipio} - {self.sigla_uf}"


class Categoria_Cadastro_Pessoal(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    description = models.CharField(max_length=255, null=True, verbose_name='Descrição Categoria')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = 'Categoria Cadastro Pessoal'
    def __str__(self):
        return self.description


class Cadastro_Pessoal(models.Model):
    NATUREZA_CHOICES = (
        ('PF', 'Pessoa Física'),
        ('PJ', 'Pessoa Jurídica')
    )

    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    categoria = models.ForeignKey(Categoria_Cadastro_Pessoal, on_delete=models.SET_NULL, null=True, verbose_name='Categoria Cadastro')
    razao_social = models.CharField(verbose_name='Nome ou Razão Social', max_length=255, null=True)
    natureza_juridica = models.CharField(verbose_name='Natureza Jurídica', max_length=2, choices=NATUREZA_CHOICES, null=True)
    nome_fantasia = models.CharField(max_length=255, null=True, blank=True, verbose_name='Nome Fantasia')
    cpf_cnpj = models.CharField(verbose_name='CPF/CNPJ', max_length=40, null=True, unique=True, error_messages={'unique':'CPF ou CNPJ já cadastrado!'})
    numero_rg = models.CharField(max_length=255, null=True, blank=True, verbose_name='Endereço')
    endereco = models.CharField(max_length=255, null=True, blank=True, verbose_name='Endereço')
    municipio = models.ForeignKey(Cadastro_Municipios, null=True, on_delete=models.CASCADE, verbose_name='Município')
    cep_endereco = models.CharField(max_length=50, null=True, blank=True, verbose_name='CEP')
    data_nascimento = models.DateField(verbose_name='Data Nascimento', null=True, blank=True)
    contato_01 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Contato 01')
    contato_02 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Contato 02')
    email_01 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Email 01')
    email_02 = models.CharField(max_length=100, null=True, blank=True, verbose_name='Email 02')
    profissao = models.CharField(max_length=100, null=True, blank=True, verbose_name='Profissão')
    description = models.TextField(null=True, blank=True, verbose_name='Descrição')
    avatar = ResizedImageField(size=[128, 128], default='avatars/clients/default-avatar.jpeg', upload_to='avatars/clients')
    is_active = models.BooleanField(default=1, null=True, verbose_name='Ativo')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural = 'Cadastro Pessoal'
    def __str__(self):
        return self.razao_social

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField
import uuid
# Create your models here.
class MyAppPermissions(models.Model):
    class Meta:
        managed = False  # No database table creation or deletion operations will be performed for this model.
        permissions = [
            ("gerenciar_usuarios", "Gerenciar Usuários"),
        ]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    job_function = models.CharField(max_length=255, null=True, verbose_name='Cargo ou Função')
    cpf =  models.CharField(max_length=255, null=True, verbose_name='CPF')
    bio = models.TextField(default=None, null=True, verbose_name='Biografia')
    birthday = models.DateField(null=True, verbose_name='Data Nascimento')
    avatar = ResizedImageField(size=[128, 128], default='avatars/users/default-avatar.jpg', upload_to='avatars/users')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'User Profile'
    def __str__(self):
        return self.user.first_name

users/forms.py
from django import forms
from django.db import models
from administrator.models import Allowed_Emails
from .models import Profile
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, EmailValidator
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
import uuid, os
from PIL import Image

class Profileform(forms.ModelForm): 
    job_function = forms.CharField(
        label='Função', max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-alt'}))
        
    cpf =  forms.CharField(
        label='CPF',
        validators=[RegexValidator(r'(^\d{3}\.\d{3}\.\d{3}\-\d{2}$)', message='Formato CPF inválido!')],
        widget=forms.TextInput(attrs={'class': 'form-control form-control-alt'}))
    
    bio = forms.CharField(
        label='Bio',
        required=False,
        widget=forms.Textarea(attrs={'cols': 6, 'rows': 4, 'class': 'form-control form-control-alt'}))
    
    birthday = forms.DateField(
        label='Data Nascimento',
        required=False,
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date', 'class': 'form-control form-control-alt'}))
        
    avatar = forms.FileField(
        label='Escolha seu novo avatar', required=False,
        widget=forms.FileInput(attrs={'class': 'form-control form-control-alt'}))
    
    def clean_avatar(self):
        if 'avatar' in self.files:
            avatar = self.cleaned_data.get('avatar')

            try:
                img = Image.open(avatar)
                img.verify()  # This verifies that it's an image
            except:
                raise forms.ValidationError('Arquivo não é uma imagem válida!')
            
            extension = os.path.splitext(avatar.name)[1]
            avatar.name = f"avatar-{str(uuid.uuid4()).replace('-', '')}{extension}"
            return avatar
        else:
            return None
    
    class Meta:
        model = Profile
        exclude = ('user', 'created_at', 'updated_at')


class Userform(forms.ModelForm):
    first_name = forms.CharField(
        label='Nome', max_length=50, min_length=3,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-alt'}))
    
    last_name = forms.CharField(
        label='Sobrenome', max_length=50, min_length=3,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-alt'}))
    
    username = forms.CharField(
        label='Usuário', max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control form-control-alt'}))
    
    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'username')


class formEmails(forms.ModelForm):
    email = forms.EmailField(
        max_length=254, required=True, label='Novo E-mail Autorizado',
        widget= forms.TextInput(attrs={'placeholder': 'Email'}))
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if Allowed_Emails.objects.filter(email=email).exists():
            raise forms.ValidationError('E-mail já autorizado!')
        else:
            return email

    class Meta:
        model = Allowed_Emails
        fields = ('email',)

users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.contrib.auth.models import User
from administrator.models import Allowed_Emails
from users.models import Profile
from django.contrib.auth.forms import PasswordChangeForm
from .forms import Profileform, Userform, formEmails
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F, ExpressionWrapper, DateTimeField, Sum, Q
from boiforte.forms import CustomSignupForm, SignupForm
import os, requests, json

@login_required
@permission_required('users.gerenciar_usuarios', raise_exception=True)
def users_index(request):
    #INDEX CADASTRO USUÁRIOS
    search = request.GET.get('search')

    if search:
        query_search = (Q(user__first_name__icontains=search) | Q(user__last_name__icontains=search) | Q(user__email__icontains=search) | Q(user__username__icontains=search))
        query_users = Profile.objects.filter(query_search)
        qtd_cadastros = query_users.count()
        str_usuarios = f"{qtd_cadastros} {'usuários encontrados' if qtd_cadastros > 1 else 'usuário encontrado'}"
    else:
        query_users = Profile.objects.all()
        qtd_cadastros = query_users.count()
        str_usuarios = f"{qtd_cadastros} {'usuários mais recentes' if qtd_cadastros > 1 else 'usuário mais recente'}"

    users = [{
        'id': user.id,
        'first_name': user.user.first_name,
        'last_name': user.user.last_name,
        'avatar': user.avatar,
        'last_login': user.user.last_login.strftime("%d/%m/%Y às %H:%M") if  user.user.last_login != None else 'Nunca Fez Login',
        'email': user.user.email,
        'username': user.user.username,
        'is_active': 'Ativo' if user.user.is_active else 'Desativado',
        'is_active_color': 'success' if user.user.is_active else 'warning',
    }for user in query_users]

    context = {
        'users': users,
        'str_usuarios': str_usuarios
    }

    return render(request, 'index_users.html', context)



@login_required
@permission_required('users.view_profile', raise_exception=True)
def user_view(request, id):
    usuario = User.objects.get(pk=request.user.id)
    try:
        profile = Profile.objects.get(user=usuario, pk=id)

        context = {
            'first_name': profile.user.first_name,
            'last_name': profile.user.last_name,
            'user_job': profile.job_function if profile.job_function else profile.user.email,
            'user_avatar': profile.avatar
        }

        return render(request, 'view_profile.html', context)
    
    except ObjectDoesNotExist:
        return render(request, 'errors/403.html')

    

@login_required
@permission_required('users.change_profile', raise_exception=True)
def user_edit(request, id):
    usuario = User.objects.get(pk=request.user.id)
    
    try:
        profile = Profile.objects.get(user=usuario, pk=id)
        if request.method == 'POST':
            formuser = Userform(request.POST, instance=usuario)
            formprofile = Profileform(request.POST, request.FILES, instance=profile)
            file_path = profile.avatar.path
            file_name = profile.avatar.name

            if formuser.is_valid():
                formuser.save()
            if formprofile.is_valid():
                if request.FILES and file_name != 'avatars/users/default-avatar.jpg':
                   os.remove(file_path)
                formprofile.save()  
                messages.success(request, 'Perfil atualizado com sucesso!', extra_tags='app_messages')
        else:
            formuser = Userform(instance=usuario)
            formprofile = Profileform(instance=profile)

        context = {
            'formusuario': formuser, 
            'formprofile': formprofile,
            'email': usuario.email,
            'user_job': profile.job_function if profile.job_function else usuario.email,
            'first_name': usuario.first_name,
            'last_name': usuario.last_name
        }

        return render(request, 'edit_profile.html', context)
    
    except ObjectDoesNotExist:
        return render(request, 'errors/403.html')
    

@login_required
@permission_required('users.gerenciar_usuarios', raise_exception=True)
def user_new(request):
    if request.method == 'POST':
        form = CustomSignupForm(request.POST)
        if form.is_valid():
            form.save(request)
            messages.success(request, 'Usuário cadastrado. Será necessário confirmar e-mail.', extra_tags='app_messages')
            return redirect('users.index')  # Ou redirecione para a página desejada
    else:
        form = CustomSignupForm()
    return render(request, 'new_user.html', {'form': form})

@login_required
@permission_required('users.gerenciar_usuarios', raise_exception=True)
def users_emails(request):
    emails = Allowed_Emails.objects.all()
    if request.method == 'POST':
        form = formEmails(request.POST)
        if form.is_valid():
            # Faça algo com o formulário válido
            form.save()
            messages.success(request, 'E-mail autorizado com sucesso.', extra_tags='app_messages')
            return render(request, 'users_emails.html', {'emails': emails, 'form':formEmails})
        else:
            form = formEmails(request.POST)
            return render(request, 'users_emails.html', {'emails': emails, 'form':form})

    else:
        return render(request, 'users_emails.html', {'emails': emails, 'form':formEmails})

users/templates/edit_profile.html
{% extends 'app.html' %}
{% block title %} Edit User {% endblock %}
{% block content %}
{% load crispy_forms_tags %}


<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2 mb-0">
    <ol class="breadcrumb breadcrumb-alt">
        <li class="breadcrumb-item fw-bold">
            <a class="link-fx text-success" href="{% url 'users.index' %}">Usuários do Sistema</a>
        </li>
        <li class="breadcrumb-item fw-bold">
            <a class="link-fx text-success" href="{% url 'user.view' user.id %}">{{ first_name }} {{ last_name }}</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            Editar Perfil
        </li>
    </ol>
</div>

<div class="d-flex py-2">
    <div class="flex-shrink-0 me-3 ms-0 overlay-container overlay-bottom">
        <img class="img-avatar img-avatar-thumb" src="{{ MEDIA_URL }}{{ user.profile.avatar }}" alt="Avatar User" style="width: 45px; height: 45px;">

    </div>
    <div class="flex-grow-1 mt-1">
        <div class="fw-bold text-dark">{{ first_name }} {{ last_name }}</div>
        <div class="fs-xs fw-semibold text-muted">{{ user_job }}</div>
    </div>
</div>


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row items-push">
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formusuario.first_name|as_crispy_field}}
            </div>
        </div>
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formusuario.last_name|as_crispy_field}}
            </div>
        </div>
    </div>
    <div class="row items-push">
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formusuario.username|as_crispy_field}}
            </div>
        </div>
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formprofile.job_function|as_crispy_field}}
            </div>
        </div>

    </div>
    <div class="row items-push">
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formprofile.cpf|as_crispy_field}}
            </div>
        </div>
        <div class="col-sm-6 col-xxl-3 mb-0">
            <div class="form-group">
                {{formprofile.birthday|as_crispy_field}}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-6 col-xxl-1 mb-0">
            <div class="form-group">
                <label class="form-label">Seu Avatar</label>
                <div class="mb-0">
                    <img class="img-avatar" style="width: 35px; height: 35px;"
                        src="{{ MEDIA_URL }}{{ user.profile.avatar }}" alt="Avatar {{ usuario.nome }}">
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xxl-5 mb-0">
            <div class="form-group">
                {{formprofile.avatar|as_crispy_field}}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-6 col-xxl-6 mb-0">
            <div class="form-group">
                {{formprofile.bio|as_crispy_field}}
            </div>
        </div>
    </div>

    <button name="bt-form-profile" type="submit" class="mt-2 btn btn-sm fs-xs btn-alt-success shadow-none">Atualizar
        Informações</button>

</form>

<hr>

<a href="{% url 'account_change_password' %}"><button class="btn btn-sm fs-xs btn-alt-primary shadow-none"></i>Redefinir Senha</button></a>

{% if messages %}
    {% for message in messages %}
        {% if 'app_messages' in message.tags %}
            <div id="django-{{ message.level_tag }}-message" style="display: none;">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<script>

    $(document).ready(function () {
        var successMessageElement = document.getElementById('django-success-message')
        var errorMessageElement = document.getElementById('django-error-message')

        if (successMessageElement) {
            var msg = successMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'success',
                icon: 'fa fa-check me-1',
                message: msg
            })
        }

        if (errorMessageElement) {
            var msg = errorMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'danger',
                icon: 'fa fa-times me-1',
                message: msg
            })
        }
    })

</script>

{% endblock %}

users/templates/index_users.html
{% extends 'app.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Users {% endblock %}

{% block content %}

<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2 mb-1">
    <ol class="breadcrumb breadcrumb-alt">
        <li class="breadcrumb-item fw-bold" aria-current="page">
            Usuários do Sistema
        </li>
    </ol>
</div>

<div class="row items-push">
    <div class="col-sm-4 col-xxl-4 mb-3">
        <form method="GET" id="search-form">
            <div class="input-group">
                <input type="text" class="form-control form-control-alt" name="search" value="{{ request.GET.search }}"
                    placeholder="Nome, Sobrenome, E-mail ou Usuário...">
                <span class="input-group-text border-0">
                    <i class="fa fa-search" id="search-btn"></i>
                </span>
            </div>
        </form>
    </div>
    
    <div class="col-sm-5 col-xxl-5 mb-3 form-group">
        {% if perms.register.add_cadastro_pessoal %}
            <a href="{% url 'user.new' %}"><button type="button" class="btn btn-secondary shadow-none fw-semibold">Novo Usuário</button></a>
        {% endif %}
    </div>
    
    <div class="col-sm-3 col-xxl-3 mb-3">
        <div class="text-end mt-2 fs-xs fw-semibold">
            <span>{{ str_usuarios }}</span>
        </div>
    </div>
</div>

<div class="tabela">
    <table class="">
        <thead>
            <th class="text-center" style="width: 5%;">
                <i class="far fa-user"></i>
            </th>
            <th style="width: 25%;">Nome</th>
            <th style="width: 15%;">Usuário</th>
            <th style="width: 25%;">Email</th>
            <th style="width: 15%;">Status</th>
            <th style="width: 15%;">Último Login</th>
        </thead>
        <tbody>
            {% for user in users %}
            <tr data-href="{% url 'user.view' user.id %}" style="cursor: pointer;">
                <td class="text-center py-1">
                    <img class="img-avatar" src="{{ MEDIA_URL }}{{user.avatar}}" alt="User Avatar"
                        style="width: 30px; height: 30px;">
                </td>
                <td class=" fs-xs text-dark">
                    {{ user.first_name }} {{ user.last_name }}
                </td>
                <td class="fs-xs text-dark">{{ user.username }}</td>
                <td class="fs-xs">{{ user.email }}</td>
                <td>
                    <span
                        class="fs-xs fw-normal d-inline-block py-1 px-3 badge bg-{{ user.is_active_color }}-light text-{{ user.is_active_color }}">{{ user.is_active }}</span>
                </td>
                <td class="fs-xs">
                    {{ user.last_login }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if messages %}
    {% for message in messages %}
        {% if 'app_messages' in message.tags %}
            <div id="django-{{ message.level_tag }}-message" style="display: none;">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<script>
    var searchBtn = $('#search-btn');
    var searchForm = $('#search-form');
    $(searchBtn).on('click', function () {
        searchForm.submit();
    })

    $(document).ready(function () {
        $(document.body).on("click", "tr[data-href]", function () {
            var url = $(this).data("href");
            window.open(url, '_self');
        })

        var successMessageElement = document.getElementById('django-success-message')
        var errorMessageElement = document.getElementById('django-error-message')

        if (successMessageElement) {
            var msg = successMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'success',
                icon: 'fa fa-check me-1',
                message: msg
            })
        }

        if (errorMessageElement) {
            var msg = errorMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'danger',
                icon: 'fa fa-times me-1',
                message: msg
            })
        }
    })

</script>


{% endblock %}

users/templates/new_user.html
{% extends 'app.html' %}
{% block title %} New User {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<style>

    #id_password1_helptext{
        font-size: 11px;
        font-weight: 500;
        color: rgb(12, 23, 56)
    }

    ul {
        list-style-type: none;
        padding: 0px;
    }

    .form-text{
    font-style: italic;
    }

</style>

<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2 mb-1">
    <ol class="breadcrumb breadcrumb-alt">
        <li class="breadcrumb-item fw-bold">
            <a class="link-fx text-success" href="{% url 'users.index' %}">Usuários do Sistema</a>
        </li>
        <li class="breadcrumb-item fw-bold" aria-current="page">
            Novo Usuário
        </li>
    </ol>
</div>


<form method="post">
    {% csrf_token %}

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-0">
            <div class="form-group">
                {{ form.first_name|as_crispy_field }}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-0">
            <div class="form-group">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-0">
            <div class="form-group">
                {{ form.username|as_crispy_field }}
            </div>
        </div>
    </div>
    

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-0">
            <div class="form-group">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-0">
            <div class="form-group">
                {{ form.password1|as_crispy_field }}
            </div>
        </div>     
    </div>

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-3">
            <div class="form-group">
                {{ form.password2|as_crispy_field }}
            </div>
        </div>
    </div>

    <div class="row items-push">
        <div class="col-sm-4 col-xxl-4 mb-1">
            <div class="form-group">
                <button type="submit" class="btn fw-normal btn-success shadow-none">Cadastrar Usuário</button>
            </div>
        </div>
    </div>
</form>

<hr>

<div class="row items-push">
    <div class="col-sm-4 col-xxl-4 mb-1">
        <a href="{%url 'users.emails'%}" class="form-group">
            <button type="submit" class="btn fw-normal btn-alt-info shadow-none">Autorizar novo E-mail</button>
        </a>
    </div>
</div>

{% endblock %}

users/templates/users_emails.html
{% extends 'app.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Users {% endblock %}

{% block content %}

<div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center py-2 mb-1">
    <ol class="breadcrumb breadcrumb-alt">
        <li class="breadcrumb-item fw-bold">
            <a class="link-fx text-success" href="{% url 'users.index' %}">Usuários do Sistema</a>
        </li>
        <li class="breadcrumb-item fw-bold">
            <a class="link-fx text-success" href="{% url 'user.new' %}">Novo Usuário</a>
        </li>
        <li class="breadcrumb-item fw-bold" aria-current="page">
            Autorizar E-mail
        </li>
    </ol>
</div>

<div class="row items-push">
    
</div>

<div class="fs-xs fw-bold mb-2">E-mails autorizados a criar uma conta nesta plataforma:</div>

{%for email in emails%}
<div class="fs-xs fw-normal mb-1 text-primary">{{ email.email }}</div>
{%endfor%}

<hr>

<div class="col-sm-5 col-xxl-5 mb-3 form-group">

    {% if perms.users.gerenciar_usuarios %}
    <form method="post">
        {%csrf_token%}
        <div class="form-group">
            {{ form.email|as_crispy_field }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn fw-normal btn-success shadow-none">Autorizar E-mail</button>
        </div>
    </form>
    {% endif %}
</div>

{% if messages %}
    {% for message in messages %}
        {% if 'app_messages' in message.tags %}
            <div id="django-{{ message.level_tag }}-message" style="display: none;">{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

<script>
    var searchBtn = $('#search-btn');
    var searchForm = $('#search-form');
    $(searchBtn).on('click', function () {
        searchForm.submit();
    })

    $(document).ready(function () {
        $(document.body).on("click", "tr[data-href]", function () {
            var url = $(this).data("href");
            window.open(url, '_self');
        })

        var successMessageElement = document.getElementById('django-success-message')
        var errorMessageElement = document.getElementById('django-error-message')

        if (successMessageElement) {
            var msg = successMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'success',
                icon: 'fa fa-check me-1',
                message: msg
            })
        }

        if (errorMessageElement) {
            var msg = errorMessageElement.innerText;
            One.helpers('jq-notify', {
                type: 'danger',
                icon: 'fa fa-times me-1',
                message: msg
            })
        }
    })

</script>


{% endblock %}